services:
  database:
    image: docker.io/postgres:latest
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
